public class myList {
    public void setMethod(){
       /* List<String> strList = new List<String>();
        List<String> strList2= new List<String>();
        
        strList2.add('USA');
        strList.add('India');
        strList.add('UK');
        system.debug('strList=>' + strList);
        system.debug('strList2=>'+ strList2);*/
        
        Set<String> strSet = new Set<String>();
        
        strSet.add('Uk');
        system.debug('strSet=>'+strSet);
    }
}